name: election_duty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔹 File handling
  file_picker: ^10.3.10 
  excel: ^4.0.6
  
  # Maps / WebView
  mappls_gl: ^1.2.1

  # 🔹 PDF
  pdf: ^3.10.0
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0
  # 🔹 HTTP (for backend later)
  http: ^1.2.0
  screenshot: ^2.1.0

  # 🔹 State management (recommended)
  provider: ^6.1.2
  google_fonts: ^6.2.1
  # 🔹 Maps (future use)
  google_maps_flutter: ^2.5.0

  dropdown_search: ^5.0.6
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true

  assets:
      - assets/images/logo.png
      - assets/images/officer_suraj.jpg