// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Whwa3Frajx7-IldPe3dwO4QLjLJaMjQ',
    appId: '1:791596517361:web:ccf9a8d33b9fb28b112650',
    messagingSenderId: '791596517361',
    projectId: 'election-duty-management',
    authDomain: 'election-duty-management.firebaseapp.com',
    storageBucket: 'election-duty-management.firebasestorage.app',
    measurementId: 'G-8EDXZGZ1J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdAo7LyydrOKgHPBJpuYSJRR5IZYqPUs',
    appId: '1:791596517361:android:f64d13bca25c285a112650',
    messagingSenderId: '791596517361',
    projectId: 'election-duty-management',
    storageBucket: 'election-duty-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEDQM-E_fVSlj-x96sM--OwhEdjbQkjeo',
    appId: '1:791596517361:ios:914709b19b1f4901112650',
    messagingSenderId: '791596517361',
    projectId: 'election-duty-management',
    storageBucket: 'election-duty-management.firebasestorage.app',
    iosBundleId: 'com.example.electionDuty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEDQM-E_fVSlj-x96sM--OwhEdjbQkjeo',
    appId: '1:791596517361:ios:914709b19b1f4901112650',
    messagingSenderId: '791596517361',
    projectId: 'election-duty-management',
    storageBucket: 'election-duty-management.firebasestorage.app',
    iosBundleId: 'com.example.electionDuty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Whwa3Frajx7-IldPe3dwO4QLjLJaMjQ',
    appId: '1:791596517361:web:9e61485d2f50eeae112650',
    messagingSenderId: '791596517361',
    projectId: 'election-duty-management',
    authDomain: 'election-duty-management.firebaseapp.com',
    storageBucket: 'election-duty-management.firebasestorage.app',
    measurementId: 'G-8N7YS84EHF',
  );
}
